# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39daacb6421e845aea033fd80cbe4ff69ad4acb7663fc2219a537527c3c25bb96a97e724033c42f535c41abefd0127e90db26b595ca43e29f0ff4d4aa658f5a9

test:
  secret_key_base: 114fbe8b0da2178b06f1daaa87ea1fb712e838344b18095496a76e1b4ad19529f5ba6b0cf71f64e171a92892b8a8d3436e2df6261942d79d610e50599a3d35be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
